kind: Workflow
name: emoji-poem
description: Writes a poem on any topic and illustrates it with inline emoji, saved as a styled HTML page.
trigger:
  kind: OnConversationStart
  id: emoji_poem
  actions:
    - kind: InvokeAzureAgent
      id: write
      agent:
        name: Creative Poet
    - kind: InvokeAzureAgent
      id: illustrate
      agent:
        name: Emoji Illustrator
